### ISSUE TITLE
Add examples or tests proving accuracy of measured data

### ISSUE THREAD

**Issue by ghost** [nullstalgia/iron-heart#2]
Hey!

One thing one naturally worries about with any data-collecting tool is the accuracy of the data. It might be helpful to convince potential users, especially ones who are more interested in the logging capability than the VRChat capability, that the heart rate measurement is free of errors. To that end:

- unit tests would be nice
- potentially more integration-y tests would be nice, or at least examples. I'm not sure what's doable, but for example perhaps capturing the raw BLE output of a H10 and feeding it to null_iron_heart on the one hand and a comparable tool on the other hand, or even wearing 2 H10s and comparing your output to e.g. Strava's output. There are probably many other possibilities.

At the moment any user is just blindly trusting in the correctness of your code. Sure, some errors would be obvious, but especially for something as sensitive as heart rate, I don't think that's sufficient.

Either way, thanks for all your work, and cheers!

**Comment by nullstalgia** [comment]
I don't disagree, which is why if you run `cargo test` you'll see that the only part *with* unit tests is the parsing of the [Heart Rate Measurement](https://github.com/nullstalgia/null_iron_heart/blob/hr_osc/src/heart_rate_measurement.rs#L74) packets from the monitor. Since we expect a collection of bytes from the Monitor, any malformities would likely come from the data supplied by the monitor (which we expect to follow the BLE/GATT specification), or something higher in the chain (`btleplug`, Windows, their BT adapter, etc).

I do plan on adding more tests to sections outside of that (I didn't even write those tests, that parsing logic and it's tests were graciously provided by [rust-cycle](https://github.com/IamfromSpace/rust-cycle)'s author's implementation), and I could perhaps add a badge showing the CI results for `cargo test`, but the mechanisms involved with [logging](https://github.com/nullstalgia/null_iron_heart/blob/hr_osc/src/logging.rs#L83) are so simple that the possible issues are likely to do with the user's system.

In spite of that, I do also plan on improving the error-handling and overall maintaining and improving the application. I've just been taking a moment to grow my Rust knowledge so I can make it *actually* maintainable and understand the tools I'm using.

**Comment by nullstalgia** [comment]
I'm not sure about integration tests due to the BLE monitor aspect (even `btleplug`'s tests are just for its own GUID logic). I might be able to get away with a WebSocket -> CSV/BPM.txt test though? Interesting challenge!

And I'll be looking at where I can put in more tests soon, fuzzing is something I haven't touched yet, but I'll see how approachable it is. Not sure if Ratatui has any helpers for that/anything else for TUI binary crates.

Feel free to close the issue if you feel what's present is satisfactory, otherwise I'll close it later when I do a test pass.

**Comment by nullstalgia** [comment]
Now that v0.2.0 is released with more unit tests and some basic integration tests (with websockets and file write testing), I feel this issue's requests have been met.
